[project]
name = "dev-environments-playground"
revision = "1.0"

[profiles.default]
db-pass = {description = "the database password", required = true}
api-key = {description = "an api key", type = "uuid", generate = true}
shared-secret = {description = "shared between different projects", providers = ["shared"], type = "password", generate = true}

[profiles.development]
db-pass = {description = "the database password", default = "tcc"}
