[project]
name = "dev-environments-playground"
revision = "1.0"

[profiles.default]
db-pass = {description = "the database password", required = true}

[profiles.development]
db-pass = {description = "the database password", default = "tcc"}
